local tags = {
	REQUIRES_TARGET = "REQUIRES_TARGET",
	CUSTOM_CAN_BE_PLAYED = "CUSTOM_CAN_BE_PLAYED",
	CUSTOM_TARGETING = "CUSTOM_TARGETING",
	TARGETS_TILE = "TARGETS_TILE",
	AFFECTS_TILE = "AFFECTS_TILE",
	AFFECTS_UNIT = "AFFECTED_UNIT",
	REQUIRES_EMPTY_NODE = "REQUIRES_EMPTY_NODE",
	REQUIRES_TARGET_IN_NODES = "REQUIRES_TARGET_IN_NODES"
}

return tags
