return function()
    local ServerScriptService = game:GetService("ServerScriptService")
    local ReplicatedStorage = game:GetService("ReplicatedStorage")
    local StatTracker = require(ServerScriptService.GameEntity.StatTracker)

    describe("Stat Tracker", function()
        it("Tests that essential functions of stat tracker works", function()
            local statTracker = StatTracker.new()
            print(statTracker)
            statTracker:_updateStat("combat", "blockApplied", 5)
            statTracker:_replaceLargestStat("combat", "largestBlock", 5)
            expect(statTracker:serialize().stats.combat.blockApplied).to.equal(5)
            expect(statTracker:serialize().stats.combat.largestBlock).to.equal(5)
            statTracker:_updateStat("combat", "blockApplied", 15)
            statTracker:_replaceLargestStat("combat", "largestBlock", 15)
            expect(statTracker:serialize().stats.combat.blockApplied).to.equal(20)
            expect(statTracker:serialize().stats.combat.largestBlock).to.equal(15)
        end)
    end)
end