name: CI checks + deployment

on:
  pull_request:
    branches:
        - production
        - test
  push:
    branches: 
        - production
        - test

jobs:
  install-tools:
    name: Install tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Set up Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Cache Aftman tools
        uses: actions/cache@v3
        with:
          path: ~/.aftman
          key: aftman-${{ hashFiles('aftman.toml') }}
      - name: Install Wally dependencies
        run: wally install

  luau-tests:
    name: Run Luau tests via Open Cloud
    runs-on: ubuntu-latest
    needs: [install-tools]
    concurrency:
      group: luau-execution
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Restore cached Aftman tools
        uses: actions/cache@v3
        with:
          path: ~/.aftman
          key: aftman-${{ hashFiles('aftman.toml') }}
      - name: Make test.sh executable
        run: chmod +x ./scripts/shell/test.sh
      - name: Run tests
        run: ./scripts/shell/test.sh test.project.json $TEST_TASK_FILE
        env:
          ROBLOX_API_KEY: ${{ secrets.TESTKEY }}
          ROBLOX_UNIVERSE_ID: ${{ vars.ROBLOX_TEST_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ vars.ROBLOX_TEST_PLACE_ID }}
          TEST_TASK_FILE: tasks/runTests.luau

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [install-tools, luau-tests]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Restore cached Aftman tools
        uses: actions/cache@v3
        with:
          path: ~/.aftman
          key: aftman-${{ hashFiles('aftman.toml') }}
      - name: Upload production build
        run: aftman run rojo upload default.project.json --api_key ${{ secrets.DEPLOYKEY }} --universe_id ${{ vars.ROBLOX_PRODUCTION_UNIVERSE_ID }} --asset_id ${{ vars.ROBLOX_PRODUCTION_PLACE_ID }}
